# Generated by Django 3.1 on 2020-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='bedroom_size',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='bedsitter',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='county',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='desposit',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='electricitybills',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='estate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='image_1',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='image_2',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='image_3',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='houses',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='houses',
            name='region',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='rent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houses',
            name='security_Excellent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='security_Good',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='security_Very_Good',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='singleroom',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houses',
            name='waterbills',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
