# Generated by Django 3.1.3 on 2020-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200915_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='bedroom_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='desposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='electricitybills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='waterbills',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
